language: go
sudo: required
dist: trusty
arch:
- mips64le
go:
  - 1.13

env:
  - DOCKER_TAG=tmp

script:
  - export DOCKER_REPO="packyzbq/cephexporter"
  - docker build -t $DOCKER_REPO:$DOCKER_TAG . -f Dockerfile-mips64;
  - docker tag $DOCKER_REPO:$DOCKER_TAG $DOCKER_REPO:$arch-latest;
  - echo "$DOCKER_REPO:$arch-latest"
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push $DOCKER_REPO:$arch-latest;
